site_name: Tech Documentation
site_url: https://docs.shaottech.com.br
site_author: Igor Ramos
theme:
  name: material
  language: pt-BR
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Mudar para o tema escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para o tema claro
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed
nav:
  - Início: index.md
  - UniFi: unifi.md
  - Linux: linux.md
  - Windows: windows.md
  - Active Directory: active-directory.md
  - Microsoft 365: microsoft-365.md
  - Troubleshooting:
    - Fix Error 303: fix-error-303.md
plugins:
  - search